#!/usr/bin/env python3
"""
CONFIG.PY - COMPLETE VERSION FOR 4 STRATEGIES + EXCHANGE API
Contains ALL parameters used by:
- Ultra-Scalp
- TTM-Squeeze 
- Quick-Momentum
- Fast-Scalp
- Exchange API connections
"""

class BotConfig:
    # ========== CORE TRADING PARAMETERS ==========
    TRADING_SYMBOLS = ["BTC", "AVAX", "SOL"]
    MODE = "paper"
    INITIAL_BALANCE = 10000
    PAPER_INITIAL_BALANCE = 10000
    CYCLE_INTERVAL = 60
    MIN_CONFIDENCE = 0.25
    MIN_DATA_POINTS = 20
    MAX_DATA_AGE_SECONDS = 300
    MAX_POSITIONS_PER_SYMBOL = 4

    # ==================== STRATEGY WEIGHTS (USED BY AGGREGATOR) ====================
    STRATEGY_WEIGHTS = {
        "Ultra-Scalp": 0.8,  # Lower weight for highest frequency
        "Fast-Scalp": 0.9,
        "Quick-Momentum": 1.0,
        "TTM-Squeeze": 1.1  # Higher weight for more reliable signals
    }
    
    # ========== EXCHANGE API CONFIGURATION ==========
    EXCHANGE_NAME = "coinbase"
    COINBASE_API_KEY = "coinbase-api_key"
    COINBASE_API_SECRET = "coinbase_api_secret"
    PASSPHRASE = "YOUR_PASSPHRASE_HERE"
 
    # ========== RISK MANAGEMENT ==========
    POSITION_SIZE_PERCENT = 25.0
    MIN_POSITION_VALUE = 2500.0
    MAX_POSITION_VALUE = 3500.0
    TARGET_POSITION_VALUE = 2500.0
    MAX_RISK_PERCENT = 2.0
    DEFAULT_STOP_LOSS_PERCENT = 0.25
    DEFAULT_TAKE_PROFIT_PERCENT = 0.60

    # ========== ULTRA-SCALP STRATEGY ==========
    ULTRA_SCALP_RSI_PERIOD = 8
    ULTRA_SCALP_SMA_PERIOD = 10
    ULTRA_SCALP_RSI_BUY_THRESHOLD = 32
    ULTRA_SCALP_RSI_SELL_THRESHOLD = 68
    ULTRA_SCALP_RSI_SLOPE_THRESHOLD = 0.1
    ULTRA_SCALP_PRICE_CHANGE_THRESHOLD = 0.0 #(?)
    ULTRA_SCALP_RSI_DISTANCE_DIVISOR = 10 #(?)
    ULTRA_SCALP_MOMENTUM_BONUS_MAX = 0.2
    ULTRA_SCALP_VOLUME_BONUS = 0.15
    ULTRA_SCALP_STOP_LOSS_PERCENT = 0.25
    ULTRA_SCALP_TAKE_PROFIT_PERCENT = 0.60
    ULTRA_SCALP_MAX_HOLD_SECONDS = 300
    ULTRA_SCALP_BASE_CONFIDENCE = 0.5
    ULTRA_SCALP_MIN_CANDLE_BODY_RATIO = 0.7
    
    # ========== FAST-SCALP STRATEGY ==========
    FAST_SCALP_RSI_PERIOD = 12
    FAST_SCALP_EMA_FAST = 8
    FAST_SCALP_EMA_SLOW = 15
    FAST_SCALP_MACD_FAST = 6
    FAST_SCALP_MACD_SLOW = 12
    FAST_SCALP_MACD_SIGNAL = 5
    FAST_SCALP_VOLUME_AVERAGE_PERIOD = 10
    FAST_SCALP_VOLUME_SURGE_MULTIPLIER = 1.05
    FAST_SCALP_RSI_DISTANCE_DIVISOR = 10
    FAST_SCALP_MACD_BONUS_MAX = 0.3
    FAST_SCALP_VOLUME_BONUS = 0.1
    FAST_SCALP_STOP_LOSS_PERCENT = 0.25
    FAST_SCALP_TAKE_PROFIT_PERCENT = 0.60
    FAST_SCALP_RSI_OVERSOLD = 38
    FAST_SCALP_RSI_OVERBOUGHT = 62
    FAST_SCALP_BASE_CONFIDENCE = 0.55
    FAST_SCALP_MAX_HOLD_SECONDS = 900
    FAST_SCALP_PRICE_CHANGE_THRESHOLD = 0.5
    FAST_SCALP_VOLUME_CONFIDENCE_BONUS = 0.2
    FAST_SCALP_MIN_CONFIDENCE = 0.2
    FAST_SCALP_PROFIT_TARGET = 0.0060
    FAST_SCALP_STOP_LOSS = 0.0025
    
    # ========== QUICK-MOMENTUM STRATEGY ==========
    QUICK_MOMENTUM_GROWTH_DETECTION_WINDOW = 18
    QUICK_MOMENTUM_PLATEAU_DETECTION_WINDOW = 12
    QUICK_MOMENTUM_MIN_GROWTH_PERCENTAGE = 0.06
    QUICK_MOMENTUM_GROWTH_CONSISTENCY_THRESHOLD = 0.35
    QUICK_MOMENTUM_PLATEAU_VOLATILITY_THRESHOLD = 0.7
    QUICK_MOMENTUM_PLATEAU_DRIFT_THRESHOLD = 0.1
    QUICK_MOMENTUM_MIN_PLATEAU_DURATION = 4
    QUICK_MOMENTUM_MIN_PATTERN_CONFIDENCE = 0.25
    QUICK_MOMENTUM_STRONG_PATTERN_CONFIDENCE = 0.5
    QUICK_MOMENTUM_USE_TECHNICAL_CONFIRMATION = True
    QUICK_MOMENTUM_CONFIRMATION_WEIGHT = 0.3
    QUICK_MOMENTUM_GCP_WEIGHT = 0.7
    QUICK_MOMENTUM_STOP_LOSS = 0.0025
    QUICK_MOMENTUM_PROFIT_TARGET = 0.008
    QUICK_MOMENTUM_MAX_HOLD_SECONDS = 5400
    QUICK_MOMENTUM_VOLUME_REQUIREMENT = 1.05
    QUICK_MOMENTUM_MIN_PATTERN_DURATION = 30
    QUICK_MOMENTUM_BASE_CONFIDENCE = 0.3

    
    # ========== TTM-SQUEEZE STRATEGY ==========
    TTM_BB_PERIOD = 22
    TTM_BB_STD_DEV = 1.8
    TTM_KC_PERIOD = 22
    TTM_KC_ATR_MULTIPLIER = 1.2
    TTM_DONCHIAN_PERIOD = 22
    TTM_CVD_PERIOD = 10
    TTM_MOMENTUM_THRESHOLD = 0.05
    TTM_STOP_LOSS_PERCENT = 0.0025
    TTM_TAKE_PROFIT_PERCENT = 0.008
    TTM_SQUEEZE_PERSISTENCE = 1
    TTM_ADX_THRESHOLD = 22
    TTM_BB_WIDTH_PERCENTILE = 35
    TTM_MAX_HOLD_SECONDS = 8000
    TTM_SQUEEZE_MAX_HOLD_SECONDS = 8000  # Alias for compatibility
    TTM_SQUEEZE_BASE_CONFIDENCE = 0.6
    TTM_SQUEEZE_SQUEEZE_BONUS = 0.2
    TTM_SQUEEZE_MOMENTUM_BONUS = 0.1
    TTM_SQUEEZE_RSI_PERIOD = 14
    TTM_SQUEEZE_RSI_BUY_THRESHOLD = 45
    TTM_SQUEEZE_RSI_SELL_THRESHOLD = 55
    TTM_SQUEEZE_MIN_CONFIDENCE = 0.15

    
    # ========== VOLUME ANALYSIS (Shared) ==========
    VOLUME_AVERAGE_PERIOD = 7
    VOLUME_SURGE_THRESHOLD = 1.05

    # ========== POSITION SIZING ==========
    ULTRA_SCALP_POSITION_SIZE_PERCENT = 15
    FAST_SCALP_POSITION_SIZE_PERCENT = 20
    TTM_SQUEEZE_POSITION_SIZE_PERCENT = 25
    QUICK_MOMENTUM_POSITION_SIZE_PERCENT = 30

    # ========== TELEGRAM NOTIFICATIONS ==========
    TELEGRAM_ENABLED = True
    TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
    TELEGRAM_CHAT_ID = "YOUR_CHAT_ID_HERE"
    NOTIFY_ALL_SIGNALS = True
    NOTIFY_TRADES = True
    NOTIFY_ERRORS = True

    # ========== HYPERLIQUID CONFIGURATION ==========
    HYPERLIQUID_API_KEY = "your_api_key_here"  # Leave empty for read-only mode
    HYPERLIQUID_API_SECRET = "your_api_secret_here"  # Leave empty for read-only mode
    HYPERLIQUID_ACCOUNT_ADDRESS = "your_wallet_address_here"  # Optional but recommended
    
    # Risk management defaults
    DYNAMIC_STOP_LOSS_PERCENT = 0.5  # Global default stop loss %
    DYNAMIC_TAKE_PROFIT_PERCENT = 1.0  # Global default take profit %
    
    # Strategy-specific risk parameters
    DYNAMIC_ULTRA_SCALP_SL = 0.25
    DYNAMIC_ULTRA_SCALP_TP = 0.5
    DYNAMIC_FAST_SCALP_SL = 0.3
    DYNAMIC_FAST_SCALP_TP = 0.6
    DYNAMIC_QUICK_MOMENTUM_SL = 0.4
    DYNAMIC_QUICK_MOMENTUM_TP = 0.8
    DYNAMIC_TTM_SQUEEZE_SL = 0.5
    DYNAMIC_TTM_SQUEEZE_TP = 1.0
    
    # Data collection settings
    DATA_COLLECTION_ENABLED = False  # Set to True if you want initial data collection
    INITIAL_DATA_COLLECTION_MINUTES = 15  # Only used if DATA_COLLECTION_ENABLED=True
    MIN_DATA_MINUTES = 20  # Minimum data required before trading

__all__ = ['BotConfig']
